FROM apache/airflow:2.10.2-python3.10

ADD requirements.txt .

# Instala dependências do sistema e o ODBC Driver 17 for SQL Server
USER root


USER airflow

# Atualiza o pip, instala o Airflow e PySpark
RUN pip install --upgrade pip && \
    pip install apache-airflow==2.10.2 pip && \
    pip install -r requirements.txt

# executar em seguida
# docker-compose up -d --no-deps --build airflow-webserver airflow-scheduler